package com.dagplanner.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class AppTheme(val themeName: String, val previewColor: Color) {
    TODOIST_ROOD("Todoist Rood",  Color(0xFFB71C1C)),
    OCEAAN_BLAUW("Oceaan Blauw", Color(0xFF1565C0)),
    WOUD_GROEN("Woud Groen",     Color(0xFF2E7D32)),
    PAARS_MAGIE("Paars Magie",   Color(0xFF6A1B9A)),
    ZONSONDERGANG("Zonsondergang", Color(0xFFE65100)),
    ROZE_BLOESEM("Roze Bloesem", Color(0xFFC2185B)),
    TEAL_MODERN("Teal Modern",   Color(0xFF00695C)),
    DONKER_PRO("Donker Pro",     Color(0xFF37474F)),
    INDIGO_NACHT("Indigo Nacht", Color(0xFF283593)),
    AMBER_WARM("Amber Warm",     Color(0xFFF57F17)),
}

fun AppTheme.toLightColorScheme(): ColorScheme = when (this) {
    AppTheme.TODOIST_ROOD -> lightColorScheme(
        primary = Color(0xFFB71C1C),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFFFCDD2),
        onPrimaryContainer = Color(0xFF4A0000),
        secondary = Color(0xFFBF360C),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFFCCBC),
        onSecondaryContainer = Color(0xFF3E0A00),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFF5E0E0),
        outline = Color(0xFFD4BABA),
        error = Color(0xFFD32F2F),
    )
    AppTheme.OCEAAN_BLAUW -> lightColorScheme(
        primary = Color(0xFF1565C0),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFD6E4FF),
        onPrimaryContainer = Color(0xFF001945),
        secondary = Color(0xFF0288D1),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFCCE5FF),
        onSecondaryContainer = Color(0xFF001E30),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFE8EDF4),
        outline = Color(0xFFBDC7D8),
        error = Color(0xFFD32F2F),
    )
    AppTheme.WOUD_GROEN -> lightColorScheme(
        primary = Color(0xFF2E7D32),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFC8E6C9),
        onPrimaryContainer = Color(0xFF00210A),
        secondary = Color(0xFF558B2F),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFDCEDC8),
        onSecondaryContainer = Color(0xFF1B2F00),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFE0EDE0),
        outline = Color(0xFFB8CFBA),
        error = Color(0xFFD32F2F),
    )
    AppTheme.PAARS_MAGIE -> lightColorScheme(
        primary = Color(0xFF6A1B9A),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFE1BEE7),
        onPrimaryContainer = Color(0xFF210036),
        secondary = Color(0xFF7B1FA2),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFE8D5F5),
        onSecondaryContainer = Color(0xFF2D0045),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFF0E4F7),
        outline = Color(0xFFCDB8D8),
        error = Color(0xFFD32F2F),
    )
    AppTheme.ZONSONDERGANG -> lightColorScheme(
        primary = Color(0xFFE65100),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFFFE0B2),
        onPrimaryContainer = Color(0xFF4A1700),
        secondary = Color(0xFFBF360C),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFFCCBC),
        onSecondaryContainer = Color(0xFF3E0A00),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFF5EAE0),
        outline = Color(0xFFD4C0B0),
        error = Color(0xFFD32F2F),
    )
    AppTheme.ROZE_BLOESEM -> lightColorScheme(
        primary = Color(0xFFC2185B),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFFCE4EC),
        onPrimaryContainer = Color(0xFF45001E),
        secondary = Color(0xFFAD1457),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFAD5E5),
        onSecondaryContainer = Color(0xFF3D001E),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFF7E4ED),
        outline = Color(0xFFD4B8C8),
        error = Color(0xFFD32F2F),
    )
    AppTheme.TEAL_MODERN -> lightColorScheme(
        primary = Color(0xFF00695C),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFB2DFDB),
        onPrimaryContainer = Color(0xFF00201C),
        secondary = Color(0xFF00796B),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFCCECE8),
        onSecondaryContainer = Color(0xFF002925),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFE0EFED),
        outline = Color(0xFFB0CFC8),
        error = Color(0xFFD32F2F),
    )
    AppTheme.DONKER_PRO -> lightColorScheme(
        primary = Color(0xFF37474F),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFECEFF1),
        onPrimaryContainer = Color(0xFF0D1618),
        secondary = Color(0xFF546E7A),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFE8EEF1),
        onSecondaryContainer = Color(0xFF1B2428),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFE8ECEE),
        outline = Color(0xFFBCC6CB),
        error = Color(0xFFD32F2F),
    )
    AppTheme.INDIGO_NACHT -> lightColorScheme(
        primary = Color(0xFF283593),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFC5CAE9),
        onPrimaryContainer = Color(0xFF060E30),
        secondary = Color(0xFF1A237E),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFBBCCF0),
        onSecondaryContainer = Color(0xFF04082A),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFE8EAF6),
        outline = Color(0xFFB0B8D8),
        error = Color(0xFFD32F2F),
    )
    AppTheme.AMBER_WARM -> lightColorScheme(
        primary = Color(0xFFF57F17),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFFFF8E1),
        onPrimaryContainer = Color(0xFF4A2500),
        secondary = Color(0xFFFF8F00),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFFF3E0),
        onSecondaryContainer = Color(0xFF3D2200),
        background = Color(0xFFF8F9FA),
        onBackground = Color(0xFF1A1C1E),
        surface = Color.White,
        onSurface = Color(0xFF1A1C1E),
        surfaceVariant = Color(0xFFF5F0E0),
        outline = Color(0xFFD4C8A0),
        error = Color(0xFFD32F2F),
    )
}

fun AppTheme.toDarkColorScheme(): ColorScheme = when (this) {
    AppTheme.TODOIST_ROOD -> darkColorScheme(
        primary = Color(0xFFEF9A9A),
        onPrimary = Color(0xFF680000),
        primaryContainer = Color(0xFF8B0000),
        onPrimaryContainer = Color(0xFFFFCDD2),
        secondary = Color(0xFFFFAB91),
        onSecondary = Color(0xFF5C1A00),
        secondaryContainer = Color(0xFF7D2900),
        onSecondaryContainer = Color(0xFFFFCCBC),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF4E3535),
        outline = Color(0xFF9E8080),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.OCEAAN_BLAUW -> darkColorScheme(
        primary = Color(0xFF90CAF9),
        onPrimary = Color(0xFF003064),
        primaryContainer = Color(0xFF00478C),
        onPrimaryContainer = Color(0xFFD6E4FF),
        secondary = Color(0xFF81D4FA),
        onSecondary = Color(0xFF003549),
        secondaryContainer = Color(0xFF004D6B),
        onSecondaryContainer = Color(0xFFCCE5FF),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF42474E),
        outline = Color(0xFF8C9199),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.WOUD_GROEN -> darkColorScheme(
        primary = Color(0xFFA5D6A7),
        onPrimary = Color(0xFF003910),
        primaryContainer = Color(0xFF1B5E20),
        onPrimaryContainer = Color(0xFFC8E6C9),
        secondary = Color(0xFFC5E1A5),
        onSecondary = Color(0xFF1A3300),
        secondaryContainer = Color(0xFF2E5000),
        onSecondaryContainer = Color(0xFFDCEDC8),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF394940),
        outline = Color(0xFF839E88),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.PAARS_MAGIE -> darkColorScheme(
        primary = Color(0xFFCE93D8),
        onPrimary = Color(0xFF3C006E),
        primaryContainer = Color(0xFF560B8B),
        onPrimaryContainer = Color(0xFFE1BEE7),
        secondary = Color(0xFFE1BEE7),
        onSecondary = Color(0xFF4A006E),
        secondaryContainer = Color(0xFF6A0080),
        onSecondaryContainer = Color(0xFFE8D5F5),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF4A3558),
        outline = Color(0xFF9C82A5),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.ZONSONDERGANG -> darkColorScheme(
        primary = Color(0xFFFFAB91),
        onPrimary = Color(0xFF7D2400),
        primaryContainer = Color(0xFFBF360C),
        onPrimaryContainer = Color(0xFFFFE0B2),
        secondary = Color(0xFFFF8A65),
        onSecondary = Color(0xFF5C1A00),
        secondaryContainer = Color(0xFF7D2900),
        onSecondaryContainer = Color(0xFFFFCCBC),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF4E3D2A),
        outline = Color(0xFF9E8C70),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.ROZE_BLOESEM -> darkColorScheme(
        primary = Color(0xFFF48FB1),
        onPrimary = Color(0xFF700038),
        primaryContainer = Color(0xFF8E0040),
        onPrimaryContainer = Color(0xFFFCE4EC),
        secondary = Color(0xFFF8BBD0),
        onSecondary = Color(0xFF64003C),
        secondaryContainer = Color(0xFF880050),
        onSecondaryContainer = Color(0xFFFAD5E5),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF4E3040),
        outline = Color(0xFF9E8090),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.TEAL_MODERN -> darkColorScheme(
        primary = Color(0xFF80CBC4),
        onPrimary = Color(0xFF003830),
        primaryContainer = Color(0xFF00504A),
        onPrimaryContainer = Color(0xFFB2DFDB),
        secondary = Color(0xFFB2DFDB),
        onSecondary = Color(0xFF003835),
        secondaryContainer = Color(0xFF005048),
        onSecondaryContainer = Color(0xFFCCECE8),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF304845),
        outline = Color(0xFF829C99),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.DONKER_PRO -> darkColorScheme(
        primary = Color(0xFFB0BEC5),
        onPrimary = Color(0xFF1C2C33),
        primaryContainer = Color(0xFF2C3E46),
        onPrimaryContainer = Color(0xFFECEFF1),
        secondary = Color(0xFFB0BEC5),
        onSecondary = Color(0xFF23353C),
        secondaryContainer = Color(0xFF344956),
        onSecondaryContainer = Color(0xFFE8EEF1),
        background = Color(0xFF0F1113),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF0F1113),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF2A3238),
        outline = Color(0xFF7A888E),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.INDIGO_NACHT -> darkColorScheme(
        primary = Color(0xFF9FA8DA),
        onPrimary = Color(0xFF0C1560),
        primaryContainer = Color(0xFF1A237E),
        onPrimaryContainer = Color(0xFFC5CAE9),
        secondary = Color(0xFFBBC4F5),
        onSecondary = Color(0xFF041060),
        secondaryContainer = Color(0xFF1A237E),
        onSecondaryContainer = Color(0xFFBBCCF0),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF2D3355),
        outline = Color(0xFF7880A5),
        error = Color(0xFFEF9A9A),
    )
    AppTheme.AMBER_WARM -> darkColorScheme(
        primary = Color(0xFFFFCC80),
        onPrimary = Color(0xFF7A4000),
        primaryContainer = Color(0xFFB05E00),
        onPrimaryContainer = Color(0xFFFFF8E1),
        secondary = Color(0xFFFFE082),
        onSecondary = Color(0xFF6A4000),
        secondaryContainer = Color(0xFF8C5500),
        onSecondaryContainer = Color(0xFFFFF3E0),
        background = Color(0xFF1A1C1E),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF1A1C1E),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF4E4030),
        outline = Color(0xFF9E9070),
        error = Color(0xFFEF9A9A),
    )
}
